version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:${PORT}'

  postgres:
    image: postgres:latest
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DATABASE}
