version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - '3000:3000'

  postgres:
    image: postgres:latest
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
